// COUNTRIES
export const GET_COUNTRIES_LIST = 'GET_COUNTRIES_LIST';
export const GET_COUNTRIES_SITES = 'GET_COUNTRIES_SITES';
export const GET_COUNTRIES_SPECIES = 'GET_COUNTRIES_SPECIES';
export const GET_COUNTRIES_POPULATIONS = 'GET_COUNTRIES_POPULATIONS';
export const GET_COUNTRIES_GEOM = 'GET_COUNTRIES_GEOM';
export const SET_COUNTRY_PARAMS = 'SET_COUNTRY_PARAMS';
export const SET_COUNTRY_SEARCH = 'SET_COUNTRY_SEARCH';

// SITES
export const GET_SITES_LIST = 'GET_SITES_LIST';
export const GET_SITES_DETAIL = 'GET_SITES_DETAIL';
export const SET_SITES_PARAMS = 'SET_SITES_PARAMS';

// SPECIES
export const GET_SPECIES_LIST = 'GET_SPECIES_LIST';
export const GET_SPECIES_SITES = 'GET_SPECIES_SITES';
export const GET_SPECIES_POPULATION = 'GET_SPECIES_POPULATION';
export const GET_SPECIES_THREATS= 'GET_SPECIES_THREATS';
export const GET_SPECIES_HABITATS = 'GET_SPECIES_HABITATS';
