// COUNTRIES
export const GET_COUNTRIES_LIST = 'GET_COUNTRIES_LIST';
export const GET_COUNTRIES_SITES = 'GET_COUNTRIES_SITES';
export const GET_COUNTRIES_SPECIES = 'GET_COUNTRIES_SPECIES';
export const GET_COUNTRIES_POPULATIONS = 'GET_COUNTRIES_POPULATIONS';
export const GET_COUNTRIES_GEOM = 'GET_COUNTRIES_GEOM';
export const SET_COUNTRY_SELECTED = 'SET_COUNTRY_SELECTED';
export const SET_COUNTRY_CAT_SELECTED = 'SET_COUNTRY_CAT_SELECTED';

// SITES
export const GET_SITES_LIST = 'GET_SITES_LIST';

// SPECIES
export const GET_SPECIES_LIST = 'GET_SPECIES_LIST';
export const GET_SPECIES_DATA = 'GET_SPECIES_DATA';
